name: K3s Pod Monitoring Workflow

on:
  workflow_dispatch

jobs:
  pod-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          chmod +x install_script.sh
          ./install_script.sh

      - name: Install My Application with Secrets
        run: |
          # Install your app using the values from GitHub Secrets
          helm install k3s myrelease \
            --set secrets.keys.GENAI_API_KEY=${{ secrets.GENAI_API_KEY }} \
            --set secrets.keys.SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }} \
            --set secrets.keys.SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
          
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Pod Monitoring Script
        run: python pod_monitoring.py
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
          PROMETHEUS_URL: ${{ env.PROMETHEUS_IP }}
